---

- name: Install the package "zsh"
  apt:
    name: zsh
    state: present

- name: Install the package "git"
  apt:
    name: git
    state: present

- name: Install oh-my-zsh
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: /usr/local/share/oh-my-zsh

- name: Download antigen.zsh
  get_url:
    url: http://git.io/antigen
    dest: "/home/{{ USER }}/.antigen.zsh"
    mode: 0644

- name: Configure oh-my-zsh
  copy:
    src: /.zshrc
    dest: "/home/{{ USER }}/.vimrc"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: 0644
